const util = require("util");
const base64url = require("base64url");
const moment = require("moment-timezone");
const nodemailer = require("nodemailer");
var { google } = require("googleapis");

module.exports = {
  send: async function (auth, element, youtubevideo) {
    return new Promise(async (res, rej) => {
      // console.log("Element : ");
      // console.log(util.inspect(element, { showHidden: false, depth: null }));
      // console.log(
      //   "\nYoutube Video : \n" +
      //     util.inspect(youtubevideo, { showHidden: false, depth: null })
      // );

      const transport = nodemailer.createTransport({
        // service: "gmail",
        host: "smtp.gmail.com",
        port: 465,
        secure: true,
        auth: {
          type: "OAuth2",
          user: "multimediagkjwrungkut@gmail.com",
          clientId: auth._clientId,
          clientSecret: auth._clientSecret,
          refreshToken: auth.credentials.refresh_token,
          accessToken: auth.credentials.access_token,
          expires: auth.credentials.expiry_date,
        },
      });

      const emailOptions = {
        from:
          "Multimedia GKJW Jemaat Rungkut <multimediagkjwrungkut@gmail.com>",
        to: element.email,
        cc: "mikhawardhana@gmail.com",
        subject: "Youtube Automation Upload API",
      };

      const mailOptions = {
        from:
          "Multimedia GKJW Jemaat Rungkut <multimediagkjwrungkut@gmail.com>",
        to: element.email,
        cc: "mikhawardhana@gmail.com",
        subject: "Multimedia GKJW Rungkut Youtube Channel",
        // text: "Hello from gmail email using API"
        html: this.formatEmail(youtubevideo),
      };

      await transport
        .sendMail(mailOptions)
        .then((response) => {
          res({
            status: "completed",
            data: response,
          });
        })
        .catch((err) => {
          res({
            status: "error",
            error: err,
          });
        });

      //   console.log(this.formatEmail(youtubevideo));
    });
  },
  formatEmail: function (youtubevideo) {
    var html = [
      '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n',
      '<html style="margin: 0; padding: 0;"\n',
      '	xmlns="http://www.w3.org/1999/xhtml">\n',
      "	<head>\n",
      '		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n',
      "		<title></title>\n",
      '		<meta http-equiv="X-UA-Compatible" content="IE=edge" />\n',
      '		<meta name="viewport" content="width=device-width" />\n',
      '		<style type="text/css">\n',
      "            @media only screen and (min-width: 620px) {\n",
      "                .wrapper {\n",
      "                    min-width: 600px !important;\n",
      "                }\n",
      "                .wrapper h1 {\n",
      "                }\n",
      "                .wrapper h1 {\n",
      "                    font-size: 64px !important;\n",
      "                    line-height: 63px !important;\n",
      "                }\n",
      "                .wrapper h2 {\n",
      "                }\n",
      "                .wrapper h2 {\n",
      "                    font-size: 30px !important;\n",
      "                    line-height: 38px !important;\n",
      "                }\n",
      "                .wrapper h3 {\n",
      "                }\n",
      "                .wrapper h3 {\n",
      "                    font-size: 22px !important;\n",
      "                    line-height: 31px !important;\n",
      "                }\n",
      "                .column {\n",
      "                }\n",
      "                .wrapper .size-8 {\n",
      "                    font-size: 8px !important;\n",
      "                    line-height: 14px !important;\n",
      "                }\n",
      "                .wrapper .size-9 {\n",
      "                    font-size: 9px !important;\n",
      "                    line-height: 16px !important;\n",
      "                }\n",
      "                .wrapper .size-10 {\n",
      "                    font-size: 10px !important;\n",
      "                    line-height: 18px !important;\n",
      "                }\n",
      "                .wrapper .size-11 {\n",
      "                    font-size: 11px !important;\n",
      "                    line-height: 19px !important;\n",
      "                }\n",
      "                .wrapper .size-12 {\n",
      "                    font-size: 12px !important;\n",
      "                    line-height: 19px !important;\n",
      "                }\n",
      "                .wrapper .size-13 {\n",
      "                    font-size: 13px !important;\n",
      "                    line-height: 21px !important;\n",
      "                }\n",
      "                .wrapper .size-14 {\n",
      "                    font-size: 14px !important;\n",
      "                    line-height: 21px !important;\n",
      "                }\n",
      "                .wrapper .size-15 {\n",
      "                    font-size: 15px !important;\n",
      "                    line-height: 23px !important;\n",
      "                }\n",
      "                .wrapper .size-16 {\n",
      "                    font-size: 16px !important;\n",
      "                    line-height: 24px !important;\n",
      "                }\n",
      "                .wrapper .size-17 {\n",
      "                    font-size: 17px !important;\n",
      "                    line-height: 26px !important;\n",
      "                }\n",
      "                .wrapper .size-18 {\n",
      "                    font-size: 18px !important;\n",
      "                    line-height: 26px !important;\n",
      "                }\n",
      "                .wrapper .size-20 {\n",
      "                    font-size: 20px !important;\n",
      "                    line-height: 28px !important;\n",
      "                }\n",
      "                .wrapper .size-22 {\n",
      "                    font-size: 22px !important;\n",
      "                    line-height: 31px !important;\n",
      "                }\n",
      "                .wrapper .size-24 {\n",
      "                    font-size: 24px !important;\n",
      "                    line-height: 32px !important;\n",
      "                }\n",
      "                .wrapper .size-26 {\n",
      "                    font-size: 26px !important;\n",
      "                    line-height: 34px !important;\n",
      "                }\n",
      "                .wrapper .size-28 {\n",
      "                    font-size: 28px !important;\n",
      "                    line-height: 36px !important;\n",
      "                }\n",
      "                .wrapper .size-30 {\n",
      "                    font-size: 30px !important;\n",
      "                    line-height: 38px !important;\n",
      "                }\n",
      "                .wrapper .size-32 {\n",
      "                    font-size: 32px !important;\n",
      "                    line-height: 40px !important;\n",
      "                }\n",
      "                .wrapper .size-34 {\n",
      "                    font-size: 34px !important;\n",
      "                    line-height: 43px !important;\n",
      "                }\n",
      "                .wrapper .size-36 {\n",
      "                    font-size: 36px !important;\n",
      "                    line-height: 43px !important;\n",
      "                }\n",
      "                .wrapper .size-40 {\n",
      "                    font-size: 40px !important;\n",
      "                    line-height: 47px !important;\n",
      "                }\n",
      "                .wrapper .size-44 {\n",
      "                    font-size: 44px !important;\n",
      "                    line-height: 50px !important;\n",
      "                }\n",
      "                .wrapper .size-48 {\n",
      "                    font-size: 48px !important;\n",
      "                    line-height: 54px !important;\n",
      "                }\n",
      "                .wrapper .size-56 {\n",
      "                    font-size: 56px !important;\n",
      "                    line-height: 60px !important;\n",
      "                }\n",
      "                .wrapper .size-64 {\n",
      "                    font-size: 64px !important;\n",
      "                    line-height: 63px !important;\n",
      "                }\n",
      "            }\n",
      "        </style>\n",
      '		<meta name="x-apple-disable-message-reformatting" />\n',
      '		<style type="text/css">\n',
      "            body {\n",
      "                margin: 0;\n",
      "                padding: 0;\n",
      "            }\n",
      "            table {\n",
      "                border-collapse: collapse;\n",
      "                table-layout: fixed;\n",
      "            }\n",
      "            * {\n",
      "                line-height: inherit;\n",
      "            }\n",
      "            [x-apple-data-detectors] {\n",
      "                color: inherit !important;\n",
      "                text-decoration: none !important;\n",
      "            }\n",
      "            .wrapper .footer__share-button a:hover,\n",
      "            .wrapper .footer__share-button a:focus {\n",
      "                color: #ffffff !important;\n",
      "            }\n",
      "            .btn a:hover,\n",
      "            .btn a:focus,\n",
      "            .footer__share-button a:hover,\n",
      "            .footer__share-button a:focus,\n",
      "            .email-footer__links a:hover,\n",
      "            .email-footer__links a:focus {\n",
      "                opacity: 0.8;\n",
      "            }\n",
      "            .preheader,\n",
      "            .header,\n",
      "            .layout,\n",
      "            .column {\n",
      "                transition: width 0.25s ease-in-out, max-width 0.25s ease-in-out;\n",
      "            }\n",
      "            .preheader td {\n",
      "                padding-bottom: 8px;\n",
      "            }\n",
      "            .layout,\n",
      "            div.header {\n",
      "                max-width: 400px !important;\n",
      "                -fallback-width: 95% !important;\n",
      "                width: calc(100% - 20px) !important;\n",
      "            }\n",
      "            div.preheader {\n",
      "                max-width: 360px !important;\n",
      "                -fallback-width: 90% !important;\n",
      "                width: calc(100% - 60px) !important;\n",
      "            }\n",
      "            .snippet,\n",
      "            .webversion {\n",
      "                float: none !important;\n",
      "            }\n",
      "            .stack .column {\n",
      "                max-width: 400px !important;\n",
      "                width: 100% !important;\n",
      "            }\n",
      "            .fixed-width.has-border {\n",
      "                max-width: 402px !important;\n",
      "            }\n",
      "            .fixed-width.has-border .layout__inner {\n",
      "                box-sizing: border-box;\n",
      "            }\n",
      "            .snippet,\n",
      "            .webversion {\n",
      "                width: 50% !important;\n",
      "            }\n",
      "            .ie .btn {\n",
      "                width: 100%;\n",
      "            }\n",
      "            .ie .stack .column,\n",
      "            .ie .stack .gutter {\n",
      "                display: table-cell;\n",
      "                float: none !important;\n",
      "            }\n",
      "            .ie div.preheader,\n",
      "            .ie .email-footer {\n",
      "                max-width: 560px !important;\n",
      "                width: 560px !important;\n",
      "            }\n",
      "            .ie .snippet,\n",
      "            .ie .webversion {\n",
      "                width: 280px !important;\n",
      "            }\n",
      "            .ie div.header,\n",
      "            .ie .layout {\n",
      "                max-width: 600px !important;\n",
      "                width: 600px !important;\n",
      "            }\n",
      "            .ie .two-col .column {\n",
      "                max-width: 300px !important;\n",
      "                width: 300px !important;\n",
      "            }\n",
      "            .ie .three-col .column,\n",
      "            .ie .narrow {\n",
      "                max-width: 200px !important;\n",
      "                width: 200px !important;\n",
      "            }\n",
      "            .ie .wide {\n",
      "                width: 400px !important;\n",
      "            }\n",
      "            .ie .stack.fixed-width.has-border,\n",
      "            .ie .stack.has-gutter.has-border {\n",
      "                max-width: 602px !important;\n",
      "                width: 602px !important;\n",
      "            }\n",
      "            .ie .stack.two-col.has-gutter .column {\n",
      "                max-width: 290px !important;\n",
      "                width: 290px !important;\n",
      "            }\n",
      "            .ie .stack.three-col.has-gutter .column,\n",
      "            .ie .stack.has-gutter .narrow {\n",
      "                max-width: 188px !important;\n",
      "                width: 188px !important;\n",
      "            }\n",
      "            .ie .stack.has-gutter .wide {\n",
      "                max-width: 394px !important;\n",
      "                width: 394px !important;\n",
      "            }\n",
      "            .ie .stack.two-col.has-gutter.has-border .column {\n",
      "                max-width: 292px !important;\n",
      "                width: 292px !important;\n",
      "            }\n",
      "            .ie .stack.three-col.has-gutter.has-border .column,\n",
      "            .ie .stack.has-gutter.has-border .narrow {\n",
      "                max-width: 190px !important;\n",
      "                width: 190px !important;\n",
      "            }\n",
      "            .ie .stack.has-gutter.has-border .wide {\n",
      "                max-width: 396px !important;\n",
      "                width: 396px !important;\n",
      "            }\n",
      "            .ie .fixed-width .layout__inner {\n",
      "                border-left: 0 none white !important;\n",
      "                border-right: 0 none white !important;\n",
      "            }\n",
      "            .ie .layout__edges {\n",
      "                display: none;\n",
      "            }\n",
      "            .mso .layout__edges {\n",
      "                font-size: 0;\n",
      "            }\n",
      "            .layout-fixed-width,\n",
      "            .mso .layout-full-width {\n",
      "                background-color: #ffffff;\n",
      "            }\n",
      "            @media only screen and (min-width: 620px) {\n",
      "                .column,\n",
      "                .gutter {\n",
      "                    display: table-cell;\n",
      "                    float: none !important;\n",
      "                    vertical-align: top;\n",
      "                }\n",
      "                div.preheader,\n",
      "                .email-footer {\n",
      "                    max-width: 560px !important;\n",
      "                    width: 560px !important;\n",
      "                }\n",
      "                .snippet,\n",
      "                .webversion {\n",
      "                    width: 280px !important;\n",
      "                }\n",
      "                div.header,\n",
      "                .layout,\n",
      "                .one-col .column {\n",
      "                    max-width: 600px !important;\n",
      "                    width: 600px !important;\n",
      "                }\n",
      "                .fixed-width.has-border,\n",
      "                .fixed-width.x_has-border,\n",
      "                .has-gutter.has-border,\n",
      "                .has-gutter.x_has-border {\n",
      "                    max-width: 602px !important;\n",
      "                    width: 602px !important;\n",
      "                }\n",
      "                .two-col .column {\n",
      "                    max-width: 300px !important;\n",
      "                    width: 300px !important;\n",
      "                }\n",
      "                .three-col .column,\n",
      "                .column.narrow,\n",
      "                .column.x_narrow {\n",
      "                    max-width: 200px !important;\n",
      "                    width: 200px !important;\n",
      "                }\n",
      "                .column.wide,\n",
      "                .column.x_wide {\n",
      "                    width: 400px !important;\n",
      "                }\n",
      "                .two-col.has-gutter .column,\n",
      "                .two-col.x_has-gutter .column {\n",
      "                    max-width: 290px !important;\n",
      "                    width: 290px !important;\n",
      "                }\n",
      "                .three-col.has-gutter .column,\n",
      "                .three-col.x_has-gutter .column,\n",
      "                .has-gutter .narrow {\n",
      "                    max-width: 188px !important;\n",
      "                    width: 188px !important;\n",
      "                }\n",
      "                .has-gutter .wide {\n",
      "                    max-width: 394px !important;\n",
      "                    width: 394px !important;\n",
      "                }\n",
      "                .two-col.has-gutter.has-border .column,\n",
      "                .two-col.x_has-gutter.x_has-border .column {\n",
      "                    max-width: 292px !important;\n",
      "                    width: 292px !important;\n",
      "                }\n",
      "                .three-col.has-gutter.has-border .column,\n",
      "                .three-col.x_has-gutter.x_has-border .column,\n",
      "                .has-gutter.has-border .narrow,\n",
      "                .has-gutter.x_has-border .narrow {\n",
      "                    max-width: 190px !important;\n",
      "                    width: 190px !important;\n",
      "                }\n",
      "                .has-gutter.has-border .wide,\n",
      "                .has-gutter.x_has-border .wide {\n",
      "                    max-width: 396px !important;\n",
      "                    width: 396px !important;\n",
      "                }\n",
      "            }\n",
      "            @supports (display: flex) {\n",
      "                @media only screen and (min-width: 620px) {\n",
      "                    .fixed-width.has-border .layout__inner {\n",
      "                        display: flex !important;\n",
      "                    }\n",
      "                }\n",
      "            }\n",
      "            @media only screen and (-webkit-min-device-pixel-ratio: 2),\n",
      "                only screen and (min--moz-device-pixel-ratio: 2),\n",
      "                only screen and (-o-min-device-pixel-ratio: 2/1),\n",
      "                only screen and (min-device-pixel-ratio: 2),\n",
      "                only screen and (min-resolution: 192dpi),\n",
      "                only screen and (min-resolution: 2dppx) {\n",
      "                .fblike {\n",
      "                    background-image: url(https://i7.createsend1.com/static/eb/master/13-the-blueprint-3/images/fblike@2x.png) !important;\n",
      "                }\n",
      "                .tweet {\n",
      "                    background-image: url(https://i8.createsend1.com/static/eb/master/13-the-blueprint-3/images/tweet@2x.png) !important;\n",
      "                }\n",
      "                .linkedinshare {\n",
      "                    background-image: url(https://i9.createsend1.com/static/eb/master/13-the-blueprint-3/images/lishare@2x.png) !important;\n",
      "                }\n",
      "                .forwardtoafriend {\n",
      "                    background-image: url(https://i10.createsend1.com/static/eb/master/13-the-blueprint-3/images/forward@2x.png) !important;\n",
      "                }\n",
      "            }\n",
      "            @media (max-width: 321px) {\n",
      "                .fixed-width.has-border .layout__inner {\n",
      "                    border-width: 1px 0 !important;\n",
      "                }\n",
      "                .layout,\n",
      "                .stack .column {\n",
      "                    min-width: 320px !important;\n",
      "                    width: 320px !important;\n",
      "                }\n",
      "                .border {\n",
      "                    display: none;\n",
      "                }\n",
      "                .has-gutter .border {\n",
      "                    display: table-cell;\n",
      "                }\n",
      "            }\n",
      "            .mso div {\n",
      "                border: 0 none white !important;\n",
      "            }\n",
      "            .mso .w560 .divider {\n",
      "                margin-left: 260px !important;\n",
      "                margin-right: 260px !important;\n",
      "            }\n",
      "            .mso .w360 .divider {\n",
      "                margin-left: 160px !important;\n",
      "                margin-right: 160px !important;\n",
      "            }\n",
      "            .mso .w260 .divider {\n",
      "                margin-left: 110px !important;\n",
      "                margin-right: 110px !important;\n",
      "            }\n",
      "            .mso .w160 .divider {\n",
      "                margin-left: 60px !important;\n",
      "                margin-right: 60px !important;\n",
      "            }\n",
      "            .mso .w354 .divider {\n",
      "                margin-left: 157px !important;\n",
      "                margin-right: 157px !important;\n",
      "            }\n",
      "            .mso .w250 .divider {\n",
      "                margin-left: 105px !important;\n",
      "                margin-right: 105px !important;\n",
      "            }\n",
      "            .mso .w148 .divider {\n",
      "                margin-left: 54px !important;\n",
      "                margin-right: 54px !important;\n",
      "            }\n",
      "            .mso .size-8,\n",
      "            .ie .size-8 {\n",
      "                font-size: 8px !important;\n",
      "                line-height: 14px !important;\n",
      "            }\n",
      "            .mso .size-9,\n",
      "            .ie .size-9 {\n",
      "                font-size: 9px !important;\n",
      "                line-height: 16px !important;\n",
      "            }\n",
      "            .mso .size-10,\n",
      "            .ie .size-10 {\n",
      "                font-size: 10px !important;\n",
      "                line-height: 18px !important;\n",
      "            }\n",
      "            .mso .size-11,\n",
      "            .ie .size-11 {\n",
      "                font-size: 11px !important;\n",
      "                line-height: 19px !important;\n",
      "            }\n",
      "            .mso .size-12,\n",
      "            .ie .size-12 {\n",
      "                font-size: 12px !important;\n",
      "                line-height: 19px !important;\n",
      "            }\n",
      "            .mso .size-13,\n",
      "            .ie .size-13 {\n",
      "                font-size: 13px !important;\n",
      "                line-height: 21px !important;\n",
      "            }\n",
      "            .mso .size-14,\n",
      "            .ie .size-14 {\n",
      "                font-size: 14px !important;\n",
      "                line-height: 21px !important;\n",
      "            }\n",
      "            .mso .size-15,\n",
      "            .ie .size-15 {\n",
      "                font-size: 15px !important;\n",
      "                line-height: 23px !important;\n",
      "            }\n",
      "            .mso .size-16,\n",
      "            .ie .size-16 {\n",
      "                font-size: 16px !important;\n",
      "                line-height: 24px !important;\n",
      "            }\n",
      "            .mso .size-17,\n",
      "            .ie .size-17 {\n",
      "                font-size: 17px !important;\n",
      "                line-height: 26px !important;\n",
      "            }\n",
      "            .mso .size-18,\n",
      "            .ie .size-18 {\n",
      "                font-size: 18px !important;\n",
      "                line-height: 26px !important;\n",
      "            }\n",
      "            .mso .size-20,\n",
      "            .ie .size-20 {\n",
      "                font-size: 20px !important;\n",
      "                line-height: 28px !important;\n",
      "            }\n",
      "            .mso .size-22,\n",
      "            .ie .size-22 {\n",
      "                font-size: 22px !important;\n",
      "                line-height: 31px !important;\n",
      "            }\n",
      "            .mso .size-24,\n",
      "            .ie .size-24 {\n",
      "                font-size: 24px !important;\n",
      "                line-height: 32px !important;\n",
      "            }\n",
      "            .mso .size-26,\n",
      "            .ie .size-26 {\n",
      "                font-size: 26px !important;\n",
      "                line-height: 34px !important;\n",
      "            }\n",
      "            .mso .size-28,\n",
      "            .ie .size-28 {\n",
      "                font-size: 28px !important;\n",
      "                line-height: 36px !important;\n",
      "            }\n",
      "            .mso .size-30,\n",
      "            .ie .size-30 {\n",
      "                font-size: 30px !important;\n",
      "                line-height: 38px !important;\n",
      "            }\n",
      "            .mso .size-32,\n",
      "            .ie .size-32 {\n",
      "                font-size: 32px !important;\n",
      "                line-height: 40px !important;\n",
      "            }\n",
      "            .mso .size-34,\n",
      "            .ie .size-34 {\n",
      "                font-size: 34px !important;\n",
      "                line-height: 43px !important;\n",
      "            }\n",
      "            .mso .size-36,\n",
      "            .ie .size-36 {\n",
      "                font-size: 36px !important;\n",
      "                line-height: 43px !important;\n",
      "            }\n",
      "            .mso .size-40,\n",
      "            .ie .size-40 {\n",
      "                font-size: 40px !important;\n",
      "                line-height: 47px !important;\n",
      "            }\n",
      "            .mso .size-44,\n",
      "            .ie .size-44 {\n",
      "                font-size: 44px !important;\n",
      "                line-height: 50px !important;\n",
      "            }\n",
      "            .mso .size-48,\n",
      "            .ie .size-48 {\n",
      "                font-size: 48px !important;\n",
      "                line-height: 54px !important;\n",
      "            }\n",
      "            .mso .size-56,\n",
      "            .ie .size-56 {\n",
      "                font-size: 56px !important;\n",
      "                line-height: 60px !important;\n",
      "            }\n",
      "            .mso .size-64,\n",
      "            .ie .size-64 {\n",
      "                font-size: 64px !important;\n",
      "                line-height: 63px !important;\n",
      "            }\n",
      "        </style>\n",
      '		<style type="text/css">\n',
      "            @import url(https://fonts.googleapis.com/css?family=Ubuntu:400, 700, 400italic, 700italic);\n",
      "        </style>\n",
      '		<link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700,400italic,700italic" rel="stylesheet" type="text/css" />\n',
      '		<style type="text/css">\n',
      "            body {\n",
      "                background-color: #fff;\n",
      "            }\n",
      "            .logo a:hover,\n",
      "            .logo a:focus {\n",
      "                color: #000 !important;\n",
      "            }\n",
      "            .mso .layout-has-border {\n",
      "                border-top: 1px solid #ccc;\n",
      "                border-bottom: 1px solid #ccc;\n",
      "            }\n",
      "            .mso .layout-has-bottom-border {\n",
      "                border-bottom: 1px solid #ccc;\n",
      "            }\n",
      "            .mso .border,\n",
      "            .ie .border {\n",
      "                background-color: #ccc;\n",
      "            }\n",
      "            .mso h1,\n",
      "            .ie h1 {\n",
      "            }\n",
      "            .mso h1,\n",
      "            .ie h1 {\n",
      "                font-size: 64px !important;\n",
      "                line-height: 63px !important;\n",
      "            }\n",
      "            .mso h2,\n",
      "            .ie h2 {\n",
      "            }\n",
      "            .mso h2,\n",
      "            .ie h2 {\n",
      "                font-size: 30px !important;\n",
      "                line-height: 38px !important;\n",
      "            }\n",
      "            .mso h3,\n",
      "            .ie h3 {\n",
      "            }\n",
      "            .mso h3,\n",
      "            .ie h3 {\n",
      "                font-size: 22px !important;\n",
      "                line-height: 31px !important;\n",
      "            }\n",
      "            .mso .layout__inner,\n",
      "            .ie .layout__inner {\n",
      "            }\n",
      "            .mso .footer__share-button p {\n",
      "            }\n",
      "            .mso .footer__share-button p {\n",
      "                font-family: sans-serif;\n",
      "            }\n",
      "             .im {\n",
      "              color: #000000 !important;\n",
      "             }\n",
      "        </style>\n",
      '		<meta name="robots" content="noindex,nofollow" />\n',
      '		<meta property="og:title" content="Multimedia GKJW Rungkut" />\n',
      "	</head>\n",
      "	<!--[if mso]>\n",
      '	<body class="mso">\n',
      "		<![endif]-->\n",
      '		<body class="no-padding" style="margin: 0; padding: 0; -webkit-text-size-adjust: 100%;">\n',
      '			<table class="wrapper" style="border-collapse: collapse; table-layout: fixed; min-width: 320px; width: 100%; background-color: #fff;" cellpadding="0" cellspacing="0" role="presentation">\n',
      "				<tbody>\n",
      "					<tr>\n",
      "						<td>\n",
      '							<div role="banner">\n',
      '								<div class="preheader" style="margin: 0 auto; max-width: 560px; min-width: 280px; width: 280px; width: calc(28000% - 167440px);">\n',
      '									<div style="border-collapse: collapse; display: table; width: 100%;">\n',
      "										<div\n",
      '                                        class="snippet"\n',
      '                                        style="\n',
      "                                            display: table-cell;\n",
      "                                            float: left;\n",
      "                                            font-size: 12px;\n",
      "                                            line-height: 19px;\n",
      "                                            max-width: 280px;\n",
      "                                            min-width: 140px;\n",
      "                                            width: 140px;\n",
      "                                            width: calc(14000% - 78120px);\n",
      "                                            padding: 10px 0 5px 0;\n",
      "                                            color: #adb3b9;\n",
      "                                            font-family: sans-serif;\n",
      '                                        "\n',
      "                                    ></div>\n",
      "										<div\n",
      '                                        class="webversion"\n',
      '                                        style="\n',
      "                                            display: table-cell;\n",
      "                                            float: left;\n",
      "                                            font-size: 12px;\n",
      "                                            line-height: 19px;\n",
      "                                            max-width: 280px;\n",
      "                                            min-width: 139px;\n",
      "                                            width: 139px;\n",
      "                                            width: calc(14100% - 78680px);\n",
      "                                            padding: 10px 0 5px 0;\n",
      "                                            text-align: right;\n",
      "                                            color: #adb3b9;\n",
      "                                            font-family: sans-serif;\n",
      '                                        "\n',
      "                                    ></div>\n",
      "									</div>\n",
      "								</div>\n",
      '								<div class="header" style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px);" id="emb-email-header-container">\n',
      "									<div\n",
      '                                    class="logo emb-logo-margin-box"\n',
      '                                    style="\n',
      "                                        font-size: 26px;\n",
      "                                        line-height: 32px;\n",
      "                                        margin-top: 9px;\n",
      "                                        margin-bottom: 20px;\n",
      "                                        color: #000;\n",
      "                                        font-family: Garamond, Adobe Garamond Pro, Palatino, Times New Roman, serif;\n",
      "                                        margin-left: 20px;\n",
      "                                        margin-right: 20px;\n",
      '                                    "\n',
      '                                    align="center"\n',
      "                                >\n",
      '										<div class="logo-center" style="font-size: 26px !important; line-height: 32px !important;" align="center" id="emb-email-header">Multimedia GKJW Rungkut</div>\n',
      "									</div>\n",
      "								</div>\n",
      "							</div>\n",
      "							<div>\n",
      '								<div style="background-color: #281557;">\n',
      "									<div\n",
      '                                    class="layout one-col stack"\n',
      '                                    style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px); overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;"\n',
      "                                >\n",
      '										<div class="layout__inner" style="border-collapse: collapse; display: table; width: 100%;">\n',
      '											<div class="column" style="text-align: left; color: #8e959c; font-size: 14px; line-height: 21px; font-family: sans-serif;">\n',
      '												<div style="margin-left: 20px; margin-right: 20px;">\n',
      '													<div style="mso-line-height-rule: exactly; line-height: 10px; font-size: 1px;">&nbsp;</div>\n',
      "												</div>\n",
      "											</div>\n",
      "										</div>\n",
      "									</div>\n",
      "								</div>\n",
      "								<div\n",
      '                                class="layout one-col fixed-width stack"\n',
      '                                style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px); overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;"\n',
      "                            >\n",
      '									<div class="layout__inner" style="border-collapse: collapse; display: table; width: 100%; background-color: #59c272;">\n',
      '										<div class="column" style="text-align: left; color: #8e959c; font-size: 14px; line-height: 21px; font-family: sans-serif;">\n',
      '											<div style="margin-left: 20px; margin-right: 20px;">\n',
      '												<div style="mso-line-height-rule: exactly; mso-text-raise: 11px; vertical-align: middle;">\n',
      '													<h1 style="margin-top: 0; margin-bottom: 0; font-style: normal; font-weight: normal; color: #000; font-size: 44px; line-height: 50px; font-family: ubuntu, sans-serif; text-align: center;">\n',
      '														<span class="font-ubuntu">Thank You !</span>\n',
      "													</h1>\n",
      "												</div>\n",
      "											</div>\n",
      "										</div>\n",
      "									</div>\n",
      "								</div>\n",
      '								<div style="mso-line-height-rule: exactly; line-height: 20px; font-size: 20px;">&nbsp;</div>\n',
      "								<div\n",
      '                                class="layout one-col fixed-width stack"\n',
      '                                style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px); overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;"\n',
      "                            >\n",
      '									<div class="layout__inner" style="border-collapse: collapse; display: table; width: 100%; background-color: #000000;">\n',
      '										<div class="column" style="text-align: left; color: #8e959c; font-size: 14px; line-height: 21px; font-family: sans-serif;">\n',
      '											<div style="font-size: 12px; font-style: normal; font-weight: normal; line-height: 19px;" align="center">\n',
      "												<img\n",
      '                                                class="gnd-corner-image gnd-corner-image-center gnd-corner-image-top gnd-corner-image-bottom"\n',
      '                                                style="border: 0; display: block; height: auto; width: 100%; max-width: 238px;"\n',
      '                                                alt=""\n',
      '                                                width="238"\n',
      '                                                src="https://www.googleapis.com/drive/v3/files/1JUSUIRBJ0nTeTPsVseGbFy7rVNsj0x9s?alt=media&key=AIzaSyAbdPHXIz1xi2UNLfRWpjbvpNH-kbyXP28"\n',
      "                                            />\n",
      "											</div>\n",
      "										</div>\n",
      "									</div>\n",
      "								</div>\n",
      '								<div style="mso-line-height-rule: exactly; line-height: 15px; font-size: 15px;">&nbsp;</div>\n',
      "								<div\n",
      '                                class="layout one-col fixed-width stack"\n',
      '                                style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px); overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;"\n',
      "                            >\n",
      '									<div class="layout__inner" style="border-collapse: collapse; display: table; width: 100%; background-color: #fff;">\n',
      '										<div class="column" style="text-align: left; color: #8e959c; font-size: 14px; line-height: 21px; font-family: sans-serif;">\n',
      '											<div style="margin-left: 20px; margin-right: 20px;">\n',
      '												<div class="divider" style="display: block; font-size: 2px; line-height: 2px; margin-left: auto; margin-right: auto; width: 40px; background-color: #ccc;">&nbsp;</div>\n',
      "											</div>\n",
      "										</div>\n",
      "									</div>\n",
      "								</div>\n",
      '								<div style="mso-line-height-rule: exactly; line-height: 49px; font-size: 49px;">&nbsp;</div>\n',
      "								<div\n",
      '                                class="layout one-col fixed-width stack"\n',
      '                                style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px); overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;"\n',
      "                            >\n",
      '									<div class="layout__inner" style="border-collapse: collapse; display: table; width: 100%; background-color: #e6e6e6;">\n',
      '										<div class="column" style="text-align: left; color: #8e959c; font-size: 14px; line-height: 21px; font-family: sans-serif;">\n',
      '											<div style="margin-left: 20px; margin-right: 20px;">\n',
      '												<div style="mso-line-height-rule: exactly; mso-text-raise: 11px; vertical-align: middle;">\n',
      '													<p class="size-20" style="margin-top: 0; margin-bottom: 0; font-size: 17px; line-height: 26px;" lang="x-size-20">Your Video has been uploaded!</p>\n',
      '													<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">Title : ' +
        youtubevideo.snippet.title +
        "\n",
      "                                                \n",
      '														<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">Description : ' +
        youtubevideo.snippet.description +
        "\n",
      "                                                \n",
      '															<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">&nbsp;</p>\n',
      '															<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">Youtube Link : </p><a href="https://www.youtube.com/watch?v=' +
        youtubevideo.id +
        '">' +
        "https://www.youtube.com/watch?v=" +
        youtubevideo.id +
        "</a>" +
        "\n",
      '															<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">Status : ' +
        youtubevideo.status.uploadStatus +
        " at " +
        this.formatDate(youtubevideo.snippet.publishedAt) +
        "\n",
      "                                                \n",
      '																<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">&nbsp;</p>\n',
      '																<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">Thanks&nbsp;for your service !&nbsp;</p>\n',
      '																<p class="size-16" style="margin-top: 20px; margin-bottom: 0; font-size: 16px; line-height: 24px;" lang="x-size-16">&nbsp;</p>\n',
      "															</div>\n",
      "														</div>\n",
      "													</div>\n",
      "												</div>\n",
      "											</div>\n",
      '											<div style="mso-line-height-rule: exactly; line-height: 20px; font-size: 20px;">&nbsp;</div>\n',
      '											<div role="contentinfo">\n',
      "												<div\n",
      '                                    class="layout email-footer stack"\n',
      '                                    style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px); overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;"\n',
      "                                >\n",
      '													<div class="layout__inner" style="border-collapse: collapse; display: table; width: 100%;">\n',
      "														<div\n",
      '                                            class="column wide"\n',
      '                                            style="text-align: left; font-size: 12px; line-height: 19px; color: #adb3b9; font-family: sans-serif; float: left; max-width: 400px; min-width: 320px; width: 320px; width: calc(8000% - 47600px);"\n',
      "                                        >\n",
      '															<div style="margin-left: 20px; margin-right: 20px; margin-top: 10px; margin-bottom: 10px;">\n',
      '																<div style="font-size: 12px; line-height: 19px;"></div>\n',
      '																<div style="font-size: 12px; line-height: 19px; margin-top: 18px;"></div>\n',
      "															</div>\n",
      "														</div>\n",
      "														<div\n",
      '                                            class="column narrow"\n',
      '                                            style="text-align: left; font-size: 12px; line-height: 19px; color: #adb3b9; font-family: sans-serif; float: left; max-width: 320px; min-width: 200px; width: 320px; width: calc(72200px - 12000%);"\n',
      "                                        >\n",
      '															<div style="margin-left: 20px; margin-right: 20px; margin-top: 10px; margin-bottom: 10px;"></div>\n',
      "														</div>\n",
      "													</div>\n",
      "												</div>\n",
      "												<div\n",
      '                                    class="layout one-col email-footer"\n',
      '                                    style="margin: 0 auto; max-width: 600px; min-width: 320px; width: 320px; width: calc(28000% - 167400px); overflow-wrap: break-word; word-wrap: break-word; word-break: break-word;"\n',
      "                                >\n",
      '													<div class="layout__inner" style="border-collapse: collapse; display: table; width: 100%;">\n',
      '														<div class="column" style="text-align: left; font-size: 12px; line-height: 19px; color: #adb3b9; font-family: sans-serif;">\n',
      '															<div style="margin-left: 20px; margin-right: 20px; margin-top: 10px; margin-bottom: 10px;">\n',
      '																<div style="font-size: 12px; line-height: 19px;"></div>\n',
      "															</div>\n",
      "														</div>\n",
      "													</div>\n",
      "												</div>\n",
      "											</div>\n",
      '											<div style="line-height: 40px; font-size: 40px;">&nbsp;</div>\n',
      "										</div>\n",
      "									</td>\n",
      "								</tr>\n",
      "							</tbody>\n",
      "						</table>\n",
      "					</body>\n",
      "				</html>\n",
      "\n",
    ].join("");
    return html;
  },
  formatDate: function (date) {
    var formatted = moment(date)
      .tz("Asia/Jakarta")
      .format("Do MMM YYYY, HH:mm:ss");

    // throw new Error(formatted);
    return formatted;
  },
};
